### ISSUE TITLE
Auto forward

### ISSUE THREAD

**Issue by adamsfour** [arvindpj007/Citadel-Email-Server-Setup#1]
Hello,

 I finally got server installed and email sending by
 using an external SMTP service.  My SMTP service will only process email from known address which under normal conditions is fine. But the issue comes when using an auto forward rule. When I  have auto forward setup  it forward emails to the service perfectly but maintains the original From address.  Is there any way to only have my domain email address in the  “From “ field for autoforward. My SMTP service only allows email from specific email address from my domain and otherwise reject the email.

**Comment by adamsfour** [comment]
In the picture attached on the left is how Citadel forms the forward messages. Which IMO is incorrect. On the right is a correctly structured forwarded message. In Citadel case it has basically resent a copy to originator. 
![IMG_4570](https://github.com/arvindpj007/Citadel-Email-Server-Setup/assets/122233494/346a8f8f-43e0-4725-9525-6339686f45df)

**Comment by arvindpj007** [comment]
Hello,

It has been sometime since I have setup this server. I did face some issues during the setup and stopped using it later on. Please try looking into the official [Citadel](https://www.citadel.org/) website to see if you can get the support you need.

**Comment by adamsfour** [comment]
Ok, I did look at the website and found nothing. I also posted a question to their support site but have not gotten any responds. Do you have a different server you recommend happy to switch if it gives me what I need.

**Comment by arvindpj007** [comment]
No, I do not have any other recommendation at this time unfortunately.
